name: "$(BuildCounter) - ${{parameters.BRANCH}}, ${{parameters.DB_UPDATE}},   $(if eq(parameters.d1, true)"

trigger: none

# variables:
#   api: $(Ccv.API_TOKENN)
#   sub: $(Ccv.SUB_CODEE)

# variables:
# - name: api
#   value: $(Ccv.API_TOKENN)

pool:
  vmImage: ubuntu-latest

parameters:
  - name: BRANCH
    type: string
    displayName: "Branch Name"
    values:
      - develop
  - name: d1
    type: boolean
    default: false
    displayName: "Check to deploy to D1"
  - name: s1
    type: boolean
    default: false
    displayName: "Check to deploy to S1"
  - name: DB_UPDATE
    type: string
    values:
      - UPDATE
      - NONE
  - name: STRATEGY
    displayName: "Deployment Mode"
    type: string
    default: 'RECREATE'
    values:
      - ROLLING_UPDATE
      - RECREATE

stages:
 - stage:
   jobs:
    - job: JOB1
      steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'

      - script: |
          echo Add other tasks to build, test, and deploy your project.
        displayName: 'Run a multi-line script'

        
      - bash: |
          # export api_token=$(API_TOKEN)
          # export sub_code=$(SUB_CODE)
          # export api_token=$(api)
          # export sub_code=$(sub)
          python python.py
          echo "##vso[task.setvariable variable=BuildCounter]$(BuildCounter)+1"
          echo "======================================================================"
          echo "                  CCV2 Build completed successfully                   "
          echo "======================================================================"
  