# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

variables:
  api_token: $(ccv.API_TOKENN)
  sub_code: $(ccv.SUB_CODEE)

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- bash: |
    # export api_token=$(API_TOKEN)
    # export sub_code=$(SUB_CODE)
    export api_token=$(api_token)
    export sub_code=$(sub_code)
    python python.py
