variables:
  counter: $[counter(variables['counter'], 1)]
  
name: "${{parameters.BRANCH}} $(variables.counter)"

trigger: none

# variables:
#   api: $(Ccv.API_TOKENN)
#   sub: $(Ccv.SUB_CODEE)

# variables:
# - name: api
#   value: $(Ccv.API_TOKENN)

# variables:
#   # runName: $[variables['Build.BuildNumber'], variables['Environment.EnvironmentName']]
#     runName: $[format('{0}_{1}_{2}', variables['System.TeamProject'], variables['Build.SourceBranchName'], variables['Environment.EnvironmentName'])]

pool:
  vmImage: ubuntu-latest

parameters:
  - name: BRANCH
    type: string
    displayName: "Branch Name"
    values:
      - develop
  - name: d1
    type: boolean
    default: false
    displayName: "Check to deploy to D1"
  - name: s1
    type: boolean
    default: false
    displayName: "Check to deploy to S1"
  - name: DB_UPDATE
    type: string
    values:
      - UPDATE
      - NONE

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
  displayName: 'Run a multi-line script'
  
- bash: |
    # export api_token=$(API_TOKEN)
    # export sub_code=$(SUB_CODE)
    # export api_token=$(api)
    # export sub_code=$(sub)
    python python.py

